# [build]
# rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Ctarget-cpu=native",
    "-Clink-arg=-fuse-ld=mold", # Use mold Linker
    "-Zshare-generics=y",       # (Nightly) Make the current crate share its generic instantiations
    "-Zthreads=0",              # (Nightly) Use improved multithreading with the recommended amount of threads.
]
