[package]
name = "nbot-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = { version = "2.0.58", features = ["full"] }
inventory = "0.3.15"
deluxe = "0.5.0"
futures = "0.3.30"

[lib]
proc-macro = true
